name: Dev Deployment

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches:
      - main         # Run on main branch

permissions:
  contents: read

jobs:
  deploy-main:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Configure AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3Ô∏è‚É£ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.4"

      # 4Ô∏è‚É£ Terraform Init & Validate
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # 5Ô∏è‚É£ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file=envs/dev.tfvars

      # 6Ô∏è‚É£ Terraform Apply (manual trigger only)
      - name: Terraform Destroy
        run: terraform destroy -var-file=envs/dev.tfvars -auto-approve

    #   # 7Ô∏è‚É£ Configure kubectl for EKS
    #   - name: Update Kubeconfig
    #     if: github.event_name == 'workflow_dispatch'
    #     run: |
    #       CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
    #       aws eks update-kubeconfig --region us-east-1 --name $CLUSTER_NAME
    #       kubectl get nodes

    #   # 8Ô∏è‚É£ Sanity Test - Create namespace
    #   - name: Create sanity-test namespace
    #     if: github.event_name == 'workflow_dispatch'
    #     run: |
    #       kubectl create namespace sanity-test || echo "Namespace already exists"
    #       kubectl get ns

    #   # 9Ô∏è‚É£ Sanity Test - Deploy NGINX pod
    #   - name: Deploy NGINX Pod
    #     if: github.event_name == 'workflow_dispatch'
    #     run: |
    #       kubectl apply -f sanity-test/nginx-pod.yaml -n sanity-test
    #       kubectl get pods -n sanity-test
    #       kubectl logs nginx-test -n sanity-test

    #   # üîü Sanity Test - NGINX Deployment
    #   - name: Deploy NGINX Deployment
    #     if: github.event_name == 'workflow_dispatch'
    #     run: |
    #       kubectl apply -f sanity-test/nginx-deploy.yaml -n sanity-test
    #       kubectl get deploy -n sanity-test
    #       kubectl get pods -n sanity-test

    #   # 1Ô∏è‚É£1Ô∏è‚É£ Sanity Test - LoadBalancer Service
    #   - name: Deploy LoadBalancer Service
    #     if: github.event_name == 'workflow_dispatch'
    #     run: |
    #       kubectl apply -f sanity-test/service.yaml -n sanity-test
    #       kubectl get svc -n sanity-test
